const attributes: { [key: string]: string } = [
  "acceptCharset",
  "accessKey",
  "allowFullScreen",
  "allowTransparency",
  "autoComplete",
  "autoFocus",
  "autoPlay",
  "cellPadding",
  "cellSpacing",
  "charSet",
  "classID",
  "className",
  "colSpan",
  "contentEditable",
  "contextMenu",
  "crossOrigin",
  "dateTime",
  "encType",
  "formAction",
  "formEncType",
  "formMethod",
  "formNoValidate",
  "formTarget",
  "frameBorder",
  "hrefLang",
  "htmlFor",
  "httpEquiv",
  "inputMode",
  "keyParams",
  "keyType",
  "marginHeight",
  "marginWidth",
  "maxLength",
  "mediaGroup",
  "minLength",
  "noValidate",
  "radioGroup",
  "readOnly",
  "rowSpan",
  "spellCheck",
  "srcDoc",
  "srcLang",
  "srcSet",
  "tabIndex",
  "useMap"
].reduce((map, value) => {
  map[value.toLowerCase()] = value;
  return map;
}, {});

export default attributes;
