// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("comscore-analytics", function () {
  this.timeout(600000);
  let vars;
  let ImageBackup;
  beforeEach(async function () {
    vars = {};
  });
  it("comscore-analytics", async function () {
    // 1. Should load the script
    await driver.get("http://localhost:3000/?frontity_name=comscore-analytics");
    // Make sure the <script> was created.
    assert(
      await driver.executeScript(
        "return document.querySelector('script[src=\"https://sb.scorecardresearch.com/beacon.js\"][async]')"
      )
    );
  });
});
