// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("google-tag-manager-analytics", function () {
  this.timeout(600000);
  let vars;
  beforeEach(async function () {
    vars = {};
  });
  const pageviewHome = {
    event: "pageview",
    link: "/",
    title: "Homepage Title",
  };

  const pageviewSomePost = {
    event: "pageview",
    link: "/some-post/",
    title: "Some Post Title",
  };

  const someEvent = {
    event: "some event",
    payload: { content: "some content" },
  };
  it("google-tag-manager-analytics", async function () {
    // 1. Should load the script
    await driver.get("http://localhost:3000/?frontity_name=google-tag-manager");
    // Make sure the <script> was created.
    assert(
      await driver.executeScript(
        "return document.querySelector('script[src=\"https://www.googletagmanager.com/gtm.js?id=GTM-XXXXXX-X\"]')"
      )
    );

    // 2. Should send the first pageview
    assert.deepEqual(
      await driver.executeScript("return window.dataLayer[1]"),
      pageviewHome
    );

    // 3. Should send a pageview if the page changes
    await driver.findElement(By.id("change-link")).click();
    assert.deepEqual(
      await driver.executeScript("return window.dataLayer[2]"),
      pageviewSomePost
    );

    // 4. Should send a pageview when going back and forward
    await driver.executeScript("return window.history.back()");
    assert.deepEqual(
      await driver.executeScript("return window.dataLayer[3]"),
      pageviewHome
    );
    await driver.executeScript("return window.history.forward()");
    assert.deepEqual(
      await driver.executeScript("return window.dataLayer[4]"),
      pageviewSomePost
    );

    // 5. Should send events
    await driver.findElement(By.id("send-event")).click();
    assert.deepEqual(
      await driver.executeScript("return window.dataLayer[5]"),
      someEvent
    );
  });
});
