// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("google-ad-manager", function () {
  this.timeout(600000);
  let vars;
  beforeEach(async function () {
    vars = {};
  });
  it("google-ad-manager", async function () {
    // Test name: google-ad-manager
    // Step # | name | target | value
    // 1 | open | /?frontity_name=google-ad-manager |
    await driver.get("http://localhost:3000/?frontity_name=google-ad-manager");
    // 2 | waitForElementPresent | css=#header-ad>div>iframe | 30000
    await driver.wait(
      until.elementLocated(By.css("#header-ad>div>iframe")),
      30000
    );
    // 3 | assertElementPresent | css=#header-ad>div>iframe |
    {
      const elements = await driver.findElements(
        By.css("#header-ad>div>iframe")
      );
      assert(elements.length);
    }
    // 4 | assertElementPresent | css=#footer-ad>div>iframe |
    {
      const elements = await driver.findElements(
        By.css("#footer-ad>div>iframe")
      );
      assert(elements.length);
    }
    // 5 | click | css=button#change-link |
    await driver.findElement(By.css("button#change-link")).click();
    // 6 | assertElementPresent | css=#header-ad_post>div>iframe |
    {
      const elements = await driver.findElements(
        By.css("#header-ad_post>div>iframe")
      );
      assert(elements.length);
    }
    // 7 | assertElementPresent | css=#footer-ad_post>div>iframe |
    {
      const elements = await driver.findElements(
        By.css("#footer-ad_post>div>iframe")
      );
      assert(elements.length);
    }
    // 8 | assertElementPresent | css=#content-ad_post>div>iframe |
    {
      const elements = await driver.findElements(
        By.css("#content-ad_post>div>iframe")
      );
      assert(elements.length);
    }
    // 9 | assertElementPresent | css=#content-ad_next-post>div>iframe |
    {
      const elements = await driver.findElements(
        By.css("#content-ad_next-post>div>iframe")
      );
      assert(elements.length);
    }
    // 10 | click | css=button#change-link-gpt |
    await driver.findElement(By.css("button#change-link-gpt")).click();
    // 11 | assertElementPresent | css=#post-with-gpt-ad>div>iframe |
    {
      const elements = await driver.findElements(
        By.css("#post-with-gpt-ad>div>iframe")
      );
      assert(elements.length);
    }
  });
});
