// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("google-analytics", function () {
  this.timeout(600000);
  let vars;
  beforeEach(async function () {
    vars = {};
  });

  it("google-analytics", async function () {
    // 1. Should load the Google Analytics library
    await driver.get("http://localhost:3000/?frontity_name=google-analytics");
    // Make sure the <script> was created.
    assert(
      await driver.executeScript(
        "return document.querySelector('script[src=\"https://www.google-analytics.com/analytics.js\"][async]')"
      )
    );
    // Make sure the Google Analytics library has loaded.
    assert(await driver.executeScript("return window.ga"));

    // 2. Should have sent the first pageview
    assert.equal(
      await driver.executeScript(
        "return window.gaData['UA-XXXXXX-X'].hitcount"
      ),
      1
    );
    assert.equal(
      await driver.executeScript(
        "return window.gaData['UA-YYYYYY-Y'].hitcount"
      ),
      1
    );

    // 3. Should send a pageview if the page changes
    await driver.findElement(By.id("change-link")).click();
    // WE SHOULD CHECK HERE IF THE SENT ARGUMENTS ARE CORRECT BUT I DON'T KNOW HOW
    assert.equal(
      await driver.executeScript(
        "return window.gaData['UA-XXXXXX-X'].hitcount"
      ),
      2
    );
    assert.equal(
      await driver.executeScript(
        "return window.gaData['UA-YYYYYY-Y'].hitcount"
      ),
      2
    );

    // 4. Should send pageviews when going back and forward
    //    WE SHOULD CHECK HERE IF THE SENT ARGUMENTS ARE CORRECT BUT I DON'T
    //    KNOW HOW
    await driver.executeScript("return window.history.back()");
    assert.equal(
      await driver.executeScript(
        "return window.gaData['UA-XXXXXX-X'].hitcount"
      ),
      3
    );
    assert.equal(
      await driver.executeScript(
        "return window.gaData['UA-YYYYYY-Y'].hitcount"
      ),
      3
    );
    await driver.executeScript("return window.history.forward()");
    assert.equal(
      await driver.executeScript(
        "return window.gaData['UA-XXXXXX-X'].hitcount"
      ),
      4
    );
    assert.equal(
      await driver.executeScript(
        "return window.gaData['UA-YYYYYY-Y'].hitcount"
      ),
      4
    );

    // 5. Should send events
    await driver.findElement(By.id("send-event")).click();
    assert.equal(
      await driver.executeScript(
        "return window.gaData['UA-XXXXXX-X'].hitcount"
      ),
      5
    );
    assert.equal(
      await driver.executeScript(
        "return window.gaData['UA-YYYYYY-Y'].hitcount"
      ),
      5
    );
  });
});
