// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("head", function () {
  this.timeout(600000);
  let vars;
  beforeEach(async function () {
    vars = {};
  });
  it("head", async function () {
    await driver.get("http://localhost:3000/?site=head");
    // 1. Should have the correct title
    assert.equal(await driver.getTitle(), "The Title");

    // 2. Should have the correct description
    assert.equal(
      await driver.executeScript(
        'return document.querySelector("meta[name=\'description\']").getAttribute("content")'
      ),
      "The Description"
    );

    // 3. Should have html attributes
    assert.equal(
      await driver.executeScript(
        "return document.querySelector('html').getAttribute(\"lang\")"
      ),
      "en"
    );

    // 4. Should be able to execute javascript in a script tag
    assert.equal(
      await driver.executeScript("return window.scriptTest"),
      "pass"
    );

    // 5. Should be able to have links
    assert.equal(
      await driver.executeScript(
        'return document.querySelector(\'link[rel="canonical"]\').getAttribute("href")'
      ),
      "http://mysite.com/example"
    );

    // 5. Should be able to change body attributes
    assert.equal(
      await driver.executeScript(
        'return document.querySelector("body").getAttribute("class")'
      ),
      "new-class"
    );

    // 6. Should be able to have nonscripts
    assert(
      (
        await driver.executeScript(
          'return document.querySelector("noscript").textContent'
        )
      ).includes("foo.css")
    );

    // 7. Should be able to add inline CSS
    assert(
      await driver.executeScript(
        'return window.getComputedStyle(document.querySelector("body"))["background-color"]'
      )
    );
  });
});
