// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("html2react", function () {
  this.timeout(600000);
  let vars;
  beforeEach(async function () {
    vars = {};
  });
  it("head", async function () {
    await driver.get("http://localhost:3000?frontity_name=html2react");
    // 1. Should pass state to processors
    assert.equal(
      await driver.executeScript(
        'return window.getComputedStyle(document.querySelector("p"))["color"]'
      ),
      "rgb(0, 0, 255)"
    );

    // 2. Should re-render when the state is updated
    await driver.findElement(By.id("change-color")).click();
    assert.equal(
      await driver.executeScript(
        'return window.getComputedStyle(document.querySelector("p"))["color"]'
      ),
      "rgb(255, 0, 0)"
    );

    // 3. Should work with old processors
    assert.equal(
      await driver.executeScript(
        'return document.querySelector("span#old-processors").textContent'
      ),
      "Yes"
    );
  });
});
