// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("slot-and-fill", function () {
  this.timeout(600000);
  let vars;
  beforeEach(async function () {
    vars = {};
  });
  it("slot-and-fill", async function () {
    await driver.get("http://localhost:3000/?frontity_name=slot-and-fill");
    //1. Should show empty slots and SSR fill
    assert.equal(
      await driver.findElement(By.id("useFills-slot1-empty")).getText(),
      "useFills slot 1 empty"
    );
    assert.equal(
      await driver.findElement(By.id("useFills-slot2-empty")).getText(),
      "useFills slot 2 empty"
    );
    assert.equal(
      await driver.findElement(By.id("SSRFill")).getText(),
      "I am SSRFill"
    );

    //2. Should show first Fill
    await driver.findElement(By.id("addFill1")).click();
    assert.equal(
      await driver.findElement(By.id("Fill1")).getText(),
      "I am Fill1"
    );
    assert(!(await driver.findElements(By.id("useFills-slot1-empty"))).length);
    assert((await driver.findElements(By.id("useFills-slot2-empty"))).length);

    //3. Should show second Fill
    await driver.findElement(By.id("addFill2")).click();
    assert.equal(
      await driver.findElement(By.id("Fill2")).getText(),
      "I am Fill2"
    );
    assert(!(await driver.findElements(By.id("useFills-slot1-empty"))).length);
    assert((await driver.findElements(By.id("useFills-slot2-empty"))).length);

    //4. Should show both fills in priority order
    assert.equal(
      await driver.findElement(By.id("useFills-slot1")).getText(),
      "I am Fill2\nI am Fill1"
    );

    //5. Should show the debug fills when `state.frontity.debug` is true
    await driver.findElement(By.id("toggleDebug")).click();
    assert(!(await driver.findElements(By.id("useFills-slot1-empty"))).length);
    assert(!(await driver.findElements(By.id("useFills-slot2-empty"))).length);
    assert(
      (await driver.findElements(By.css("[data-slot-name='slot 1']"))).length
    );
    assert(
      (await driver.findElements(By.css("[data-slot-name='slot 2']"))).length
    );
  });
});
