// Generated by Selenium IDE
const { By, until } = require("selenium-webdriver");
const assert = require("assert");

describe("comscore-analytics", function () {
  beforeEach(async function () {
    await driver.get(baseUrl + "/?frontity_name=comscore-analytics");
    await driver.wait(until.titleIs("Homepage Title"), 5000);
  });

  const pageviewHome = {
    title: "Homepage Title",
    link: baseUrl + "/",
  };

  const pageviewSomePost = {
    title: "Some Post Title",
    link: baseUrl + "/some-post/",
  };

  it("should load the Comscore library", async function () {
    assert(
      await driver.executeScript(
        "return document.querySelector('script[src=\"https://sb.scorecardresearch.com/beacon.js\"][async]')"
      )
    );
  });

  it("should send the first pageview", async function () {
    assert.deepEqual(
      await driver.executeScript("return window.comscoreCalls[0]"),
      { id: "111111", ...pageviewHome }
    );
    assert.deepEqual(
      await driver.executeScript("return window.comscoreCalls[1]"),
      { id: "222222", ...pageviewHome }
    );
  });

  it("should send a pageview if the page changes", async function () {
    await driver.findElement(By.id("change-link")).click();
    await driver.wait(until.titleIs("Some Post Title"), 5000);
    assert.deepEqual(
      await driver.executeScript("return window.comscoreCalls[2]"),
      { id: "111111", ...pageviewSomePost }
    );
    assert.deepEqual(
      await driver.executeScript("return window.comscoreCalls[3]"),
      { id: "222222", ...pageviewSomePost }
    );
  });

  it("should send pageviews when going back or forward", async function () {
    await driver.findElement(By.id("change-link")).click();
    await driver.wait(until.titleIs("Some Post Title"), 5000);
    await driver.executeScript("return window.history.back()");
    await driver.wait(until.titleIs("Homepage Title"), 5000);
    assert.deepEqual(
      await driver.executeScript("return window.comscoreCalls[4]"),
      { id: "111111", ...pageviewHome }
    );
    assert.deepEqual(
      await driver.executeScript("return window.comscoreCalls[5]"),
      { id: "222222", ...pageviewHome }
    );
    await driver.executeScript("return window.history.forward()");
    await driver.wait(until.titleIs("Some Post Title"), 5000);
    assert.deepEqual(
      await driver.executeScript("return window.comscoreCalls[6]"),
      { id: "111111", ...pageviewSomePost }
    );
    assert.deepEqual(
      await driver.executeScript("return window.comscoreCalls[7]"),
      { id: "222222", ...pageviewSomePost }
    );
  });
});
